export {default as Signup} from './Signup'
export {default as SignIp} from './SignIn'
export {default as Orders} from './Orders'
export {default as Mypage} from './Mypage'
export {default as TotalView} from './TotalView'
export {default as DetailView} from './DetailView'
export {default as WishList} from '../containers/WishList'