export {default as Home} from './Home'
export {default as User} from './User'
export {default as Covid} from './Covid'
export {default as Stock} from './Stock'
export {default as Examples} from './Examples'