export {default as Home} from './Home'
export {default as User} from './User'
export {default as Total} from './Total'
export {default as Detail} from './Detail'
export {default as Wish} from './Wish'